version: '3'

services:
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - authenticationNetwork
      - storeNetwork

  authenticationDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 10
    volumes:
    - authenticationdata:/var/lib/mysql
    networks:
      - authenticationNetwork

  authenticationDatabaseMigration:
    image: authenticationdatabasemigration
    environment:
      - DATABASE_URL=authenticationDatabase
    depends_on:
      authenticationDatabase:
        condition: service_healthy
    networks:
      - authenticationNetwork

  authentication:
    image: authentication
    environment:
      - DATABASE_URL=authenticationDatabase
    depends_on:
      - authenticationDatabaseMigration
    ports:
    - 5001:5001
    networks:
       - authenticationNetwork

  storeDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 30s
      retries: 10
    ports:
      - 3306:3306
    volumes:
      - storedata:/var/lib/mysql
    networks:
      - storeNetwork

  storeDatabaseMigration:
    image: storedatabasemigration
    environment:
      - DATABASE_URL=storeDatabase
    depends_on:
      storeDatabase:
        condition: service_healthy
    networks:
      - storeNetwork

  customer:
    image: customer
    environment:
      - DATABASE_URL=storeDatabase
    depends_on:
        - storeDatabaseMigration
        - ganache-cli
    ports:
      - 5002:5002
    networks:
      - storeNetwork

  courier:
    image: courier
    environment:
      - DATABASE_URL=storeDatabase
    depends_on:
      - storeDatabaseMigration
      - ganache-cli
    ports:
      - 5003:5003
    networks:
      - storeNetwork

#  owner:
#    image: owner
#    environment:
#      - DATABASE_URL=storeDatabase
#    depends_on:
#      - storeDatabaseMigration
#    ports:
#      - 5004:5004
#    networks:
#      - storeNetwork

  ganache-cli:
    image: trufflesuite/ganache-cli
    ports:
      - 8545:8545
    networks:
      - storeNetwork
    command: [
      "--account=0xae07088da4ecd73ecb3d9d806cf391dfc4f5f15f9ee131265da8af81728a4314,10000000000000000000",
      "--account=0xb64be88dd6b89facf295f4fd0dda082efcbe95a2bb4478f5ee582b7efe88cf60,0",
      "--account=0xe76cf0bc15d593f7763749101172cec1d0a6d3cbd9e57a5b61a409df719b8f47,0",
      "--account=0xbe07088da4ecd73ecb3d9d806cf391dfaef5f15f9ee131265da8af81728a4379,0"
    ]

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - 8083:8080
      - 7077:7077
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - storeNetwork

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - 8081:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - storeNetwork

  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - 8082:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - storeNetwork

  spark:
    image: spark:v1
    ports:
      - 5004:5004
    environment:
      - PRODUCTION=True
      - DATABASE_IP=storeDatabase
    networks:
      - storeNetwork


volumes:
  authenticationdata:
  storedata:

networks:
  authenticationNetwork:
  storeNetwork: